import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { articles } from "../../../lib/content";
import { ShareButton } from "../../../components/ShareButton";

export async function generateStaticParams(){return articles.map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const a=articles.find(x=>x.slug===slug);return a?{title:a.title,description:a.dek,openGraph:{title:a.title,description:a.dek,images:[a.image],type:"article"}}:{title:"Artículo"}}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const article=articles.find(a=>a.slug===slug);if(!article)notFound();const related=articles.filter(a=>a.slug!==article.slug).slice(0,2);return <article className="article-page" data-article-slug={article.slug}><header className="article-header page-shell"><span className="eyebrow">{article.category}</span><h1>{article.title}</h1><p>{article.dek}</p><div className="article-header-meta"><div>Por <Link href={`/autores#${article.authorSlug}`}>{article.author}</Link><br/><span>{article.published} · {article.readingMinutes} min de lectura</span></div><ShareButton title={article.title}/></div></header><div className="article-hero"><img src={article.image} alt=""/></div><div className="reading-layout page-shell"><aside><div className="reading-progress"><span></span></div><p>EN ESTA HISTORIA</p>{article.body.map((s,i)=>s.heading&&<a href={`#seccion-${i}`} key={s.heading}>{s.heading}</a>)}</aside><div className="article-body">{article.body.map((section,i)=><section id={`seccion-${i}`} key={i}>{section.heading&&<h2>{section.heading}</h2>}{section.paragraphs.map(p=><p key={p}>{p}</p>)}{section.quote&&<blockquote>{section.quote}</blockquote>}</section>)}<div className="references"><span className="eyebrow">TRANSPARENCIA</span><h2>Fuentes y metodología</h2><p>Esta pieza fue revisada por el equipo editorial de Órbita. Las referencias técnicas y entrevistas completas se incorporarán con la publicación definitiva.</p></div><div className="author-card"><div className="author-initial">{article.author.charAt(0)}</div><div><span>ESCRITO POR</span><h3>{article.author}</h3><p>{article.dek}</p></div></div></div></div><section className="related page-shell"><div className="section-heading"><h2>Continúa en esta órbita</h2></div><div className="related-grid">{related.map(a=><Link href={`/articulos/${a.slug}`} key={a.slug}><img src={a.image} alt=""/><span className="eyebrow">{a.category}</span><h3>{a.title}</h3><small>{a.readingMinutes} min →</small></Link>)}</div></section></article>}
